### ISSUE TITLE
Cannot find function "p"

### ISSUE THREAD

**Issue by TaylorAndrew** [csgillespie/addinmanger#1]
Error:

     Error in tag("div", list(...)) : could not find function "p"

Once I manually load the `shiny` package it works fine. Assuming you need to add: 

     importFrom(shiny,p)

**Comment by csgillespie** [comment]
Fixed. Try

```
devtools::install_github("csgillespie/addinmanager")
addinmanager::addin_manager()
```

For info, I've moved the repo to  https://github.com/csgillespie/addinmanager/
